spring.application.name=firstspringapp
#Using wildcard "*" exposes all the endpoints while using commas "," exposes only the specified endpoints.
#management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Exclude individual endpoints from being exposed with a comma-delimited list
# management.endpoints.web.exposure.exclude=health,info

info.app.name = First Spring Boot Application
info.app.description = This is a simple Spring Boot application to demonstrate the basics of Spring Boot.
info.app.version = 1.0.0

# Defining custom properties for the application
coach.name = Mickey
team.name = Club House


# Change Spring Boot server port
# server.port = 7070

# Change the context path of the application
server.servlet.context-path= /firstspringapp