spring.application.name=springcoredemo
# Makes it so that only the classes or beans needed are loaded and none else. Even Democontroller will be only created once it is called and not automatically when app is started.
# spring.main.lazy-initialization=true   